#!/bin/bash
echo "🔑 CLERK PRODUCTION KEYS SETUP"
echo "=============================="
echo ""
echo "1. Go to: https://dashboard.clerk.com"
echo "2. Select your 'patient-oryx-39' project"
echo "3. Go to 'API Keys' in the left sidebar"
echo "4. Look for 'Production' section (you may need to switch from Development)"
echo "5. Copy these values:"
echo "   - Publishable key (starts with pk_live_)"
echo "   - Secret key (starts with sk_live_)"
echo ""
echo "6. Then run this command with your keys:"
echo "   ./update_clerk_keys.sh 'your_pk_live_key' 'your_sk_live_key'"
echo ""
echo "Need help? Ask me!"
